# Generated by Django 5.2.8 on 2026-01-07 05:49

from django.db import migrations


def seed_projects(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    if Project.objects.exists():
        return

    Project.objects.bulk_create(
        [
            Project(
                title="Personal Expense Tracker",
                description="Web app para bantayan ang gastos at budget na may simple charts.",
                live_url="https://example.com/expense-tracker",
                repo_url="https://github.com/username/expense-tracker",
                tech_stack="Django, SQLite, HTMX",
                featured=True,
                sort_order=1,
            ),
            Project(
                title="Landing Page Starter",
                description="Mabilis na template para sa mga produkto o events na mobile-friendly.",
                live_url="https://example.com/landing-starter",
                repo_url="https://github.com/username/landing-starter",
                tech_stack="HTML, CSS, Alpine.js",
                featured=False,
                sort_order=2,
            ),
            Project(
                title="Portfolio Revamp",
                description="Mas maayos na layout at structured content para sa personal site.",
                live_url="https://example.com/portfolio",
                repo_url="https://github.com/username/portfolio",
                tech_stack="Django, Tailwind",
                featured=False,
                sort_order=3,
            ),
        ]
    )


def remove_seed(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Project.objects.filter(
        title__in=[
            "Personal Expense Tracker",
            "Landing Page Starter",
            "Portfolio Revamp",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_projects, reverse_code=remove_seed),
    ]
